class AdminLte2Generator < BaseGenerator
  source_root File.expand_path('../templates', __FILE__)
  class_option :stylesheet_engine

  def main
    stylesheet_extension = options[:stylesheet_engine] || 'css'
    stylesheet_file = "app/assets/stylesheets/application.#{stylesheet_extension}"

    unless ::File.exist?(stylesheet_file)
      create_file(stylesheet_file) do
        "/* #{stylesheet_file} generated by adminlte2-rails */"
      end
    end

    inject_into_file "app/assets/stylesheets/application.#{stylesheet_extension}", "\n@import \"AdminLTE/skins/skin-blue\";", after: ' */'
    inject_into_file "app/assets/stylesheets/application.#{stylesheet_extension}", "\n@import \"AdminLTE/AdminLTE\";", after: ' */'
    inject_into_file "app/assets/stylesheets/application.#{stylesheet_extension}", "\n@import \"bootstrap\";", after: ' */'
    inject_into_file "app/assets/stylesheets/application.#{stylesheet_extension}", "\n@import \"bootstrap-sprockets\";", after: ' */'
    inject_into_file "app/assets/stylesheets/application.#{stylesheet_extension}", "\n@import \"font-awesome\";", after: ' */'

    inject_into_file "app/assets/javascripts/application.js", "//= require bootstrap-sprockets\n", after: "//= require jquery\n"
    inject_into_application_javascript('app', before: '//= require_tree')

    copy_file '_admin_lte_2_header.html.erb', 'app/views/layouts/_admin_lte_2_header.html.erb'
    copy_file '_admin_lte_2_sidebar.html.erb', 'app/views/layouts/_admin_lte_2_sidebar.html.erb'
    copy_file 'admin_lte_2.html.erb', 'app/views/layouts/admin_lte_2.html.erb'
    copy_file '_html_header.html.erb', 'app/views/application/_html_header.html.erb'
    copy_file '_social_auth_links.html.erb', 'app/views/application/_social_auth_links.html.erb'

    if yes?('Add layout to ApplicationController ? (y/n) ')
      inject_into_file 'app/controllers/application_controller.rb', "\n  layout 'admin_lte_2'\n", after: 'class ApplicationController < ActionController::Base'
    end

    if yes?('Login Page ? (y/n)')
      copy_file 'login.html.erb', 'app/views/login/login.html.erb'
    end

    if yes?('Devise ? (y/n) ')
      gem 'devise'

      run 'bundle install'
      generate 'devise:install'

      inject_into_file 'app/controllers/application_controller.rb', "\n  before_action :authenticate_user!\n", after: 'class ApplicationController < ActionController::Base'

      environment "
      config.to_prepare do
        Devise::SessionsController.layout 'admin_lte_2_login'
      end
      "
    end
  end
end
